"use client";

import { useEffect, useMemo, useState } from "react";
import { collection, onSnapshot, orderBy, query } from "firebase/firestore";
import { AlertCircle, CheckCircle2, Clock3, MessageCircle, Send, XCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useAuth } from "@/contexts/AuthContext";
import { db } from "@/lib/firebase";
import { filtrarPorSocio } from "@/lib/socio";
import { atualizarCobranca, criarCobranca, jaExisteCobrancaHoje, obterConfiguracaoCobranca, registrarLog } from "@/services/cobrancas";
import { whatsappProvider } from "@/lib/whatsapp/providers";

type Filtro = "TODOS" | "HOJE" | "AMANHA" | "ATRASO" | "ENVIADOS" | "PENDENTES";
type LogCobranca = { cliente?: string; telefone?: string; data?: string; tipo?: string; resultado?: string; provider?: string; mensagem?: string; erro?: string };
const modelos: Record<string, string> = {
  "3 dias": "Olá, {{cliente}}! Seu pagamento de {{valor}} referente a {{produto}} vence em {{vencimento}}. Obrigado, {{empresa}}.",
  "hoje": "Olá, {{cliente}}! A parcela {{parcela}}/{{totalParcelas}} de {{produto}}, no valor de {{valor}}, vence hoje. {{empresa}}.",
  "1 dia de atraso": "Olá, {{cliente}}! Identificamos que a parcela de {{produto}} no valor de {{valor}} venceu em {{vencimento}}. Fale conosco para regularizar. {{empresa}}.",
  "7 dias de atraso": "Olá, {{cliente}}! Sua parcela de {{produto}} no valor de {{valor}} está há 7 dias em atraso. Por favor, entre em contato. {{empresa}}.",
};
function vencimento(p: any) { return p.vencimento?.seconds ? new Date(p.vencimento.seconds * 1000) : new Date(p.vencimento); }
function categoria(p: any) { if (p.status === "PAGA") return ""; const hoje = new Date(); hoje.setHours(0, 0, 0, 0); const dias = Math.ceil((vencimento(p).setHours(0, 0, 0, 0) - hoje.getTime()) / 86400000); return dias < 0 ? "ATRASO" : dias === 0 ? "HOJE" : dias === 1 ? "AMANHA" : dias <= 3 ? "3DIAS" : ""; }
function tipoMensagem(p: any) { const categoriaAtual = categoria(p); return categoriaAtual === "ATRASO" ? (Math.ceil((Date.now() - vencimento(p).getTime()) / 86400000) >= 7 ? "7 dias de atraso" : "1 dia de atraso") : categoriaAtual === "HOJE" ? "hoje" : "3 dias"; }
function hoje(valor?: string) { return !!valor && new Date(valor).toDateString() === new Date().toDateString(); }

export default function CentralWhatsapp() {
  const { usuario } = useAuth();
  const [parcelas, setParcelas] = useState<any[]>([]); const [logs, setLogs] = useState<LogCobranca[]>([]); const [filtro, setFiltro] = useState<Filtro>("TODOS"); const [busca, setBusca] = useState(""); const [enviando, setEnviando] = useState<string | null>(null); const [aviso, setAviso] = useState(""); const [carregando, setCarregando] = useState(true);
  useEffect(() => { if (!usuario) return; return onSnapshot(query(collection(db, "parcelas"), orderBy("vencimento", "asc")), s => { setParcelas(filtrarPorSocio(s.docs.map(d => ({ id: d.id, ...d.data() })), usuario).filter((p: any) => p.status !== "PAGA")); setCarregando(false); }); }, [usuario]);
  useEffect(() => onSnapshot(query(collection(db, "cobrancaLogs"), orderBy("data", "desc")), s => setLogs(s.docs.map(d => d.data() as LogCobranca)), () => setLogs([])), []);
  const logDoCliente = (p: any) => logs.filter(log => log.cliente === p.clienteNome || (!!p.clienteTelefone && log.telefone === p.clienteTelefone));
  const resumo = useMemo(() => { const enviados = logs.filter(log => hoje(log.data) && log.resultado === "ENVIADA"); const erros = logs.filter(log => hoje(log.data) && log.resultado === "ERRO"); const tentativas = enviados.length + erros.length; return { ATRASO: parcelas.filter(p => categoria(p) === "ATRASO"), HOJE: parcelas.filter(p => categoria(p) === "HOJE"), AMANHA: parcelas.filter(p => categoria(p) === "AMANHA"), ENVIADOS: enviados, ERROS: erros, PENDENTES: parcelas.filter(p => !logDoCliente(p).some(log => hoje(log.data))) , TAXA: tentativas ? Math.round((enviados.length / tentativas) * 100) : 0 }; }, [parcelas, logs]);
  const lista = useMemo(() => parcelas.filter(p => { const logsCliente = logDoCliente(p); const passaFiltro = filtro === "TODOS" || (filtro === "PENDENTES" ? !logsCliente.some(log => hoje(log.data)) : filtro === "ENVIADOS" ? logsCliente.some(log => hoje(log.data) && log.resultado === "ENVIADA") : categoria(p) === filtro); const termos = [p.clienteNome, p.clienteTelefone, p.telefone, p.produtoNome, p.imei, p.cor, p.socioNome].filter(Boolean).join(" ").toLowerCase(); return passaFiltro && termos.includes(busca.toLowerCase()); }), [parcelas, logs, filtro, busca]);
  async function enviar(p: any) { setEnviando(p.id); try { const tipo = tipoMensagem(p); if (await jaExisteCobrancaHoje(p.clienteId, tipo)) { setAviso("Já existe uma cobrança desse tipo para este cliente hoje."); return; } const config = await obterConfiguracaoCobranca(); const provider = config?.providerAtivo || "WAME"; const valores: Record<string, string> = { cliente: p.clienteNome || "", produto: p.produtoNome || "", valor: Number(p.valor || 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" }), parcela: String(p.parcela || ""), totalParcelas: String(p.totalParcelas || ""), vencimento: vencimento(p).toLocaleDateString("pt-BR"), empresa: config?.empresa || "Pantoja Phone Imports" }; const mensagem = (modelos[tipo] || config?.mensagemPadrao || "").replace(/{{(.*?)}}/g, (_, chave) => valores[chave] || ""); const telefone = p.clienteTelefone || p.telefone || ""; const criada = await criarCobranca({ clienteId: p.clienteId, cliente: p.clienteNome || "", telefone, produto: p.produtoNome || "", parcela: Number(p.parcela), valor: Number(p.valor), vencimento: vencimento(p).toISOString(), tipoMensagem: tipo, status: "PENDENTE", criadoEm: new Date().toISOString(), provider, tentativas: 1, responsavel: usuario?.nome, mensagem }); try { const resultado = await whatsappProvider.send({ telefone, mensagem, provider }); const dataEnvio = new Date().toISOString(); await atualizarCobranca(criada.id, { status: resultado.status === "ENVIADA" ? "ENVIADA" : "PENDENTE", enviadoEm: dataEnvio }); await registrarLog({ cobrancaId: criada.id, data: dataEnvio, usuario: usuario?.nome || "", cliente: p.clienteNome || "", telefone, provider, mensagem, tipo, resultado: resultado.status }); setAviso(resultado.status === "ENVIADA" ? "Cobrança enviada." : "WhatsApp aberto; aguardando envio manual."); } catch (error) { const dataErro = new Date().toISOString(); await atualizarCobranca(criada.id, { status: "ERRO" }); await registrarLog({ cobrancaId: criada.id, data: dataErro, usuario: usuario?.nome || "", cliente: p.clienteNome || "", telefone, provider, mensagem, tipo, resultado: "ERRO", erro: error instanceof Error ? error.message : "Erro no provider" }); setAviso("Não foi possível enviar a cobrança."); } } finally { setEnviando(null); } }
  async function enviarTodos() { if (!confirm(`Abrir ${lista.length} cobrança(s)?`)) return; for (const parcela of lista) await enviar(parcela); }
  const cards = [{ titulo: "Clientes em atraso", valor: resumo.ATRASO.length, filtro: "ATRASO" as Filtro, icone: AlertCircle }, { titulo: "Cobranças hoje", valor: resumo.HOJE.length, filtro: "HOJE" as Filtro, icone: Clock3 }, { titulo: "Cobranças amanhã", valor: resumo.AMANHA.length, filtro: "AMANHA" as Filtro, icone: Clock3 }, { titulo: "Mensagens enviadas hoje", valor: resumo.ENVIADOS.length, filtro: "ENVIADOS" as Filtro, icone: CheckCircle2 }, { titulo: "Falhas", valor: resumo.ERROS.length, filtro: "TODOS" as Filtro, icone: XCircle }, { titulo: "Pendentes", valor: resumo.PENDENTES.length, filtro: "PENDENTES" as Filtro, icone: Clock3 }, { titulo: "Taxa de sucesso", valor: `${resumo.TAXA}%`, filtro: "TODOS" as Filtro, icone: CheckCircle2 }];
  if (carregando) return <div className="grid grid-cols-2 gap-3 xl:grid-cols-4">{Array.from({ length: 7 }).map((_, i) => <div key={i} className="h-24 animate-pulse rounded-xl bg-zinc-900" />)}</div>;
  return <div className="space-y-6">{aviso && <div className="rounded-xl border border-blue-500/30 bg-blue-500/10 p-3 text-sm text-blue-200">{aviso}</div>}<div className="grid grid-cols-2 gap-3 xl:grid-cols-4">{cards.map(({ titulo, valor, filtro: alvo, icone: Icon }) => <button onClick={() => setFiltro(alvo)} key={titulo} className={`rounded-xl border p-4 text-left ${filtro === alvo ? "border-blue-500 bg-blue-500/10" : "border-zinc-800 bg-zinc-900"}`}><Icon size={16} className="text-amber-300" /><p className="mt-2 text-xs text-zinc-400">{titulo}</p><p className="mt-1 text-2xl font-bold text-white">{valor}</p></button>)}</div><div className="flex flex-col gap-3 sm:flex-row"><Input value={busca} onChange={e => setBusca(e.target.value)} placeholder="Buscar cliente, telefone, produto, IMEI, cor ou sócio..." /><Button variant="outline" onClick={() => { setFiltro("TODOS"); setBusca(""); }}>Limpar filtros</Button><Button onClick={enviarTodos} disabled={!lista.length || !!enviando}><Send size={16} /> Enviar para todos</Button></div><div className="overflow-x-auto rounded-2xl border border-zinc-800"><table className="w-full min-w-[1180px] text-sm"><thead className="bg-zinc-900 text-zinc-400"><tr>{["Cliente", "Telefone", "Produto", "Sócio", "Parcela", "Valor", "Vencimento", "Última cobrança", "Lembretes", "Provider", "Tentativa", "WhatsApp"].map(x => <th key={x} className="p-3 text-left">{x}</th>)}</tr></thead><tbody>{lista.length ? lista.map(p => { const historico = logDoCliente(p); const ultimo = historico[0]; return <tr key={p.id} className="border-t border-zinc-800 align-top"><td className="p-3 text-white"><p>{p.clienteNome}</p>{historico.slice(0, 3).map((log, i) => <p key={i} className="mt-1 text-xs text-zinc-500">{new Date(log.data || "").toLocaleDateString("pt-BR")} · {log.resultado === "ENVIADA" ? "Mensagem enviada" : log.resultado}</p>)}</td><td className="p-3">{p.clienteTelefone || p.telefone || "-"}</td><td className="p-3">{p.produtoNome || "-"}</td><td className="p-3">{p.socioNome || "-"}</td><td className="p-3">{p.parcela}/{p.totalParcelas}</td><td className="p-3 text-green-400">{Number(p.valor || 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" })}</td><td className="p-3">{vencimento(p).toLocaleDateString("pt-BR")}</td><td className="p-3">{ultimo?.data ? new Date(ultimo.data).toLocaleString("pt-BR") : "-"}</td><td className="p-3">{historico.length}</td><td className="p-3">{ultimo?.provider || "-"}</td><td className="p-3">{ultimo?.resultado || "PENDENTE"}</td><td className="p-3"><Button size="sm" onClick={() => enviar(p)} disabled={!(p.clienteTelefone || p.telefone) || enviando === p.id}><MessageCircle size={16} /> {enviando === p.id ? "Enviando" : "Enviar"}</Button></td></tr>; }) : <tr><td colSpan={12} className="p-12 text-center text-zinc-400">Nenhuma cobrança encontrada com estes filtros.</td></tr>}</tbody></table></div></div>;
}
