"use client";
import { useEffect, useState } from "react";
import Layout from "@/components/layout/Layout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { obterConfiguracaoCobranca, salvarConfiguracaoCobranca } from "@/services/cobrancas";
import type { ConfiguracaoCobranca } from "@/types/cobranca";
const padrao: ConfiguracaoCobranca={providerAtivo:"WAME",horario:"08:00",empresa:"Pantoja Phone Imports",telefone:"",mensagemPadrao:"",assinatura:"",diasAntecedencia:[3,1,0]};
export default function Page(){const [config,setConfig]=useState<ConfiguracaoCobranca>(padrao);useEffect(()=>{obterConfiguracaoCobranca().then(x=>x&&setConfig(x))},[]);return <Layout><div className="max-w-2xl space-y-6"><div><h1 className="text-3xl font-bold text-white">Configurações da Cobrança</h1><p className="mt-2 text-zinc-400">Parâmetros independentes para a automação.</p></div><div className="space-y-4 rounded-2xl border border-zinc-800 bg-zinc-900 p-6"><label className="block text-sm text-zinc-300">Provider ativo<select value={config.providerAtivo} onChange={e=>setConfig({...config,providerAtivo:e.target.value as ConfiguracaoCobranca["providerAtivo"]})} className="mt-2 w-full rounded-lg border border-zinc-700 bg-zinc-950 p-3 text-white"><option value="WAME">Wa.me (manual)</option><option value="EVOLUTION">Evolution API</option><option value="META_CLOUD">Meta Cloud API</option><option value="Z_API">Z-API</option><option value="ULTRAMSG">UltraMsg</option></select></label>{[["Horário","horario"],["Empresa","empresa"],["Telefone","telefone"],["Mensagem padrão","mensagemPadrao"],["Assinatura","assinatura"]].map(([l,k])=><label key={k} className="block text-sm text-zinc-300">{l}<Input className="mt-2" value={String(config[k as keyof ConfiguracaoCobranca]||"")} onChange={e=>setConfig({...config,[k]:e.target.value})}/></label>)}<Button onClick={async()=>{await salvarConfiguracaoCobranca(config);alert("Configurações salvas.")}}>Salvar configurações</Button></div></div></Layout>}
